### ISSUE TITLE
User Story 001: Acceptance Testing

### ISSUE THREAD

**Issue by eliasmalik** [TwinePlatform/volunteer-dashboard#10]
Testing functionality in #6 

Related to #7 

Testing link: https://twine-dashboard-staging.herokuapp.com

Manual Testing
* [x] Login (as CB_ADMIN: Success)
* [x] Login (as VOLUNTEER_ADMIN: Success)
* [x] Login (Validation error)
* [x] Login (Unrecognised user)
* [x] Forgot/Reset password (Success)
* [x] Forgot password (Unrecognised user)
* [x] Forgot/Reset password (Non-matching passwords)
* [x] Forgot/Reset password (Invalid token)
* [x] Forgot/Reset password (Invalid email)

Dev task to complete after testing:
* [x] Reset the links in the e-mail templates to point to production

**Comment by mandsmandsmands** [comment]
TEST ID | USER STORY | TEST NAME | Result
===========================================
0001 | VOL-DASH-001 | Successful   Volunteer Admin Login, Browse and Logout | PASS
0002 | VOL-DASH-001 | Successful CB   Admin Login, Browse and Logout | PASS
0003 | VOL-DASH-001 | Failed Logins -   Negative | PASS
0004 | VOL-DASH-001 | Password reset   and Login - Positive | PASS
0005 | VOL-DASH-001 | Password reset   - Negative passwords | Some comments
0006 | VOL-DASH-001 | Password reset   - Invalid token | PASS
0007 | VOL-DASH-001 | Password reset   - Invalid email | PASS

Defects:
--
1.   CONFIRM RESET EMAIL SENT
Step: Enter the email address of a valid account to password reset and click Submit.
Actual: The dashboard login page is shown
Expected: Can we get a message saying   "Password reset e-mail sent" or something equivalent?
 
2. EMAIL HEADING
Step:    Pwd reset, enter email and submit.    Receive email:
Actual: Heading of email sent - Twine   Volunteer App
Expected:    Twine Volunteer Dashboard
 
3. ERROR MSG LAG AFTER SUBMITTING NEW PWDS
Step: Enter a password and a confirm pwd which contains no symbol but good for everything else. Submit.
Actual: Takes ages for error msg to   appear > 20 sec
Expected: Error message appears *soon*   after submit

**Comment by eliasmalik** [comment]
> CONFIRM RESET EMAIL SENT

Fix submitted in #12

> EMAIL HEADING

Template updated

> ERROR MSG LAG AFTER SUBMITTING NEW PWDS

This can't be reproduced. I suspect this will be because of the spin-up time of the staging server. After a few minutes of inactivity, the staging API server will go into idle mode. The first request to it after that has happened will take a while, since it has to wait for it to spin up again. If you clicked the reset link after leaving the app for a few minutes, this would explain it.

**Comment by mandsmandsmands** [comment]
4. Question raised whether email address is still valid for Dashboard

![image](https://user-images.githubusercontent.com/4282773/55016787-5f837080-4fe7-11e9-8367-946e47683fa4.png)

**Comment by eliasmalik** [comment]
> Question raised whether email address is still valid for Dashboard

This should eventually be changed, but since we have access to this account, we can probably go ahead for now.

#12 has now been merged, so @mandsmandsmands please let us know if there are any further comments.

**Comment by mandsmandsmands** [comment]
1. CONFIRM RESET EMAIL SENT
Step: Enter the email address of a valid account to password reset and click Submit.
Actual: Password reset e-mail has been sent
Expected: Password reset e-mail sent

PASS

**Comment by mandsmandsmands** [comment]
2. EMAIL HEADING
Step:  Pwd reset, enter email and submit.  Receive email:
Actual: Heading of email sent - Twine Volunteer Dashboard
Expected:  Twine Volunteer Dashboard
 
PASS

**Comment by mandsmandsmands** [comment]
3. ERROR MSG LAG AFTER SUBMITTING NEW PWDS
ISSUE IS REJECTED - Due to it being an 'Environmental Issue'

**Comment by mandsmandsmands** [comment]
Test Results can be found in:
Doc: https://drive.google.com/open?id=1Zg2gGW3DPAXIi9mXLtVLntVDu3Hj-G8i
Folder: https://drive.google.com/open?id=14fj-nd0Mmutcqb90FW0YLTbaApHqIEN0
