### ISSUE TITLE
🥞 tech stack

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/volunteer-dashboard#2]
place holder issue to discuss tech stack

**Comment by eliasmalik** [comment]
React - Typescript - Redux - Express

Possibly:
- https://github.com/STRML/react-grid-layout

**Comment by astroash** [comment]
Also worth researching reacts context api as a replacement for redux

**Comment by eliasmalik** [comment]
`react-redux` uses the context API. If all we want is top-level state and to avoid prop drilling, then it may be reasonable to only use the context API, but using `redux` proper also give us degrees of debuggability and testability that I don't think the context API by itself would, and also allows us to make use of various middleware for managing side-effects.

Gatsby vs CRA is mixed from what I can see. It offers SSR, code-splitting out of the box, but is also a more opinionated and requires us to jump through extra hoops to avoid GraphQL. Gatsby doesn't seem to be solving any problems that we have right now tbh, and does require learning a new config/build system. (If anything Next.js is probably a more appropriate alternative to CRA for us, but again, not sure we really need it right now).

React-hooks are orthogonal to Redux, the former concerned mainly with bringing state and lifecycle style functionality to functional components.
(https://medium.com/@dan_abramov/making-sense-of-react-hooks-fdbde8803889)
(https://www.reddit.com/r/reactjs/comments/9tto1x/are_react_hooks_going_to_kill_redux/)

On Typescript + React, the only significant complaints I can find are pretty old and/or have to do with compile time. I suggest trying it to start out with and assessing pain levels as we go.

**Comment by astroash** [comment]
Throwing this into the mix of state management options:

https://github.com/jamiebuilds/unstated#readme

**Comment by astroash** [comment]
@eliascodes can I close this?

**Comment by eliasmalik** [comment]
sure?
